# Generated by Django 3.1.7 on 2021-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='tag_line',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
